In [1]:
camas='dim_hoscamas'
habitaciones='dim_hoshab'
estreg='dim_estreg'
tiphoscam='dim_tiphoscam'
esthoscam='dim_esthoscam'
oricas='dim_oricas'
red='dim_red'
cas='dim_cas'
servicios='dim_servicios'
estenf='dim_estenf'
areas='dim_areas'
tiphoshab='dim_tiphoshab'
esthoshab='dim_esthoshab'

In [51]:
import oracledb
import pandas as pd
from sqlalchemy import create_engine
import sys
from sqlalchemy import create_engine
from sqlalchemy import text
import sys
from decouple import config

DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dw_essalud"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena4  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine4 = create_engine(cadena4)
connection4 = engine4.connect()

In [3]:
pdcamas = pd.read_sql_query(f"SELECT * FROM {camas}", con=connection4)
pdhabitaciones = pd.read_sql_query(f"SELECT * FROM {habitaciones}", con=connection4)
pdestreg = pd.read_sql_query(f"SELECT cod_est, des_est FROM {estreg}", con=connection4)
pdtiphoscam = pd.read_sql_query(f"SELECT cod_tipcam, des_tipcam FROM {tiphoscam}", con=connection4)
pdesthoscam = pd.read_sql_query(f"SELECT cod_estcam, des_estcam FROM {esthoscam}", con=connection4)
pdoricas = pd.read_sql_query(f"SELECT ori_cod, ori_nom FROM {oricas}", con=connection4)
pdred = pd.read_sql_query(f"SELECT id_red,cod_red,des_red FROM {red}", con=connection4)
pdcas = pd.read_sql_query(f"SELECT id_red,cod_cas,des_cas, ori_cas FROM {cas} where id_red is not null", con=connection4)
pdservicios = pd.read_sql_query(f"SELECT cod_ser, des_ser FROM {servicios}", con=connection4)
pdestenf = pd.read_sql_query(f"SELECT ori_cas, cod_cas as estenf_cod_cas, are_cod as estenf_are_cod, ser_cod as estenf_serv_cod, est_cod, est_des FROM {estenf}", con=connection4)
pdareas = pd.read_sql_query(f"SELECT cod_are,des_are FROM {areas}", con=connection4)
pdtiphoshab = pd.read_sql_query(f"SELECT cod_tiphab, des_tiphab FROM {tiphoshab}", con=connection4)
pdesthoshab = pd.read_sql_query(f"SELECT cod_esthab, des_esthab FROM {esthoshab}", con=connection4)

In [4]:
pdestenf

,ori_cas,estenf_cod_cas,estenf_are_cod,estenf_serv_cod,est_cod,est_des
0,1,001,03,A83,05,HEMAT. ESPECIAL 10 C
1,1,001,03,AC1,01,MED.INTERNA 3C
2,1,001,03,AC1,03,MED.INTERNA 4C
3,1,001,03,AC1,07,COVID 6C
4,1,001,03,AC1,09,COVID 7C
...,...,...,...,...,...,...
4041,1,245,06,C12,04,ATEN. INMEDIATA RN
4042,1,245,06,C11,03,PUERPERIO INMEDIATO
4043,1,245,06,C11,04,ATEN. INMEDIATA RN
4044,1,410,06,C11,01,CENTRO OBSTETRICO
4045,1,194,03,C11,02,GINECO-OBSTETRICIA

In [5]:
cas_red = pd.merge(pdcas,pdred,how='left',on='id_red')
pdoricas=pdoricas.rename(columns={"ori_cod":"ori_cas"})
ori_cas_red = pd.merge(cas_red,pdoricas,how='left',on='ori_cas')

In [6]:
cas_red

,id_red,cod_cas,des_cas,ori_cas,cod_red,des_red
0,9.0,205,H.IV VICTOR LAZARTE ECHEGARAY,1,15,RED ASISTENCIAL LA LIBERTAD ...
1,9.0,207,H.I ALBRECHT,1,15,RED ASISTENCIAL LA LIBERTAD ...
2,9.0,208,H.I PACASMAYO,1,15,RED ASISTENCIAL LA LIBERTAD ...
3,9.0,212,H.I LA ESPERANZA,1,15,RED ASISTENCIAL LA LIBERTAD ...
4,9.0,218,P.M. CARTAVIO,1,15,RED ASISTENCIAL LA LIBERTAD ...
...,...,...,...,...,...,...
513,5.0,719,SICCHEZ,3,09,RED ASISTENCIAL PIURA ...
514,1.0,485,CAP III EL OBELISCO,1,05,RED PRESTACIONAL SABOGAL ...
515,31.0,739,CENTRO NACIONAL DE TELEMEDICINA,1,99,AFESSALUD-GOF ...
516,1.0,497,CAP III LUIS NEGREIROS VEGA,1,05,RED PRESTACIONAL SABOGAL ...
517,1.0,015,H.II LIMA NORTE - CALLAO L. NEGREIROS V.,1,05,RED PRESTACIONAL SABOGAL ...

In [7]:
ori_cas_red

,id_red,cod_cas,des_cas,ori_cas,cod_red,des_red,ori_nom
0,9.0,205,H.IV VICTOR LAZARTE ECHEGARAY,1,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
1,9.0,207,H.I ALBRECHT,1,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
2,9.0,208,H.I PACASMAYO,1,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
3,9.0,212,H.I LA ESPERANZA,1,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
4,9.0,218,P.M. CARTAVIO,1,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
...,...,...,...,...,...,...,...
513,5.0,719,SICCHEZ,3,09,RED ASISTENCIAL PIURA ...,MINSA
514,1.0,485,CAP III EL OBELISCO,1,05,RED PRESTACIONAL SABOGAL ...,ESSALUD
515,31.0,739,CENTRO NACIONAL DE TELEMEDICINA,1,99,AFESSALUD-GOF ...,ESSALUD
516,1.0,497,CAP III LUIS NEGREIROS VEGA,1,05,RED PRESTACIONAL SABOGAL ...,ESSALUD
517,1.0,015,H.II LIMA NORTE - CALLAO L. NEGREIROS V.,1,05,RED PRESTACIONAL SABOGAL ...,ESSALUD

In [8]:
pdhabitaciones

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0
4,5,1,076,03,C11,03,02,"A,B",1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1
16412,16413,1,001,03,B63,07,124,13C,1,1,1
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1

In [9]:
pdareas = pdareas.rename(columns={'cod_are':'are_cod'})
pdhabitacionesv2 = pd.merge(pdhabitaciones,pdareas,how='left',on='are_cod')

In [10]:
pdhabitacionesv2

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg,des_are
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0,HOSPITALIZACION
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0,HOSPITALIZACION
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0,HOSPITALIZACION
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0,HOSPITALIZACION
4,5,1,076,03,C11,03,02,"A,B",1,1,1,HOSPITALIZACION
...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1,HOSPITALIZACION
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1,URGENCIAS / EMERGENCIA
16412,16413,1,001,03,B63,07,124,13C,1,1,1,HOSPITALIZACION
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1,HOSPITALIZACION
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1,HOSPITALIZACION

In [11]:
ori_cas_red = ori_cas_red.rename(columns={'cod_cas':'cas_cod'})
ori_cas_red = ori_cas_red.drop(columns=['ori_cas'])
pdhabitacionesv3 = pd.merge(pdhabitacionesv2,ori_cas_red,how='left',on='cas_cod')

In [12]:
pdhabitacionesv3

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg,des_are,id_red,des_cas,cod_red,des_red,ori_nom
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
4,5,1,076,03,C11,03,02,"A,B",1,1,1,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1,HOSPITALIZACION,34.0,H.II JAEN,40,RED ASISTENCIAL JAEN ...,ESSALUD
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1,URGENCIAS / EMERGENCIA,9.0,H.I PACASMAYO,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD
16412,16413,1,001,03,B63,07,124,13C,1,1,1,HOSPITALIZACION,3.0,H.N. EDGARDO REBAGLIATI MARTINS,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD

In [13]:
pdservicios = pdservicios.rename(columns={'cod_ser':'ser_cod'})
pdhabitacionesv4 = pd.merge(pdhabitacionesv3,pdservicios,how='left',on='ser_cod')

In [14]:
pdhabitacionesv4

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg,des_are,id_red,des_cas,cod_red,des_red,ori_nom,des_ser
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
4,5,1,076,03,C11,03,02,"A,B",1,1,1,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,GINECOLOGIA Y OBSTETRICIA ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1,HOSPITALIZACION,34.0,H.II JAEN,40,RED ASISTENCIAL JAEN ...,ESSALUD,PEDIATRIA ...
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1,URGENCIAS / EMERGENCIA,9.0,H.I PACASMAYO,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD,MEDICINA GENERAL ...
16412,16413,1,001,03,B63,07,124,13C,1,1,1,HOSPITALIZACION,3.0,H.N. EDGARDO REBAGLIATI MARTINS,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD,NEUROCIRUGIA VASCULAR Y TUMORES / CIR.CEREB.Y ...
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...

In [15]:
pdtiphoshab = pdtiphoshab.rename(columns={'cod_tiphab':'tip_hab'})
pdtiphoshab['tip_hab'] = pdtiphoshab['tip_hab'].str.strip()
pdhabitacionesv5 = pd.merge(pdhabitacionesv4,pdtiphoshab,how='left',on='tip_hab')

In [16]:
pdhabitacionesv5

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg,des_are,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tiphab
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN
4,5,1,076,03,C11,03,02,"A,B",1,1,1,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,GINECOLOGIA Y OBSTETRICIA ...,COMUN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1,HOSPITALIZACION,34.0,H.II JAEN,40,RED ASISTENCIAL JAEN ...,ESSALUD,PEDIATRIA ...,COMUN
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1,URGENCIAS / EMERGENCIA,9.0,H.I PACASMAYO,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD,MEDICINA GENERAL ...,COMUN
16412,16413,1,001,03,B63,07,124,13C,1,1,1,HOSPITALIZACION,3.0,H.N. EDGARDO REBAGLIATI MARTINS,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD,NEUROCIRUGIA VASCULAR Y TUMORES / CIR.CEREB.Y ...,COMUN
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN

In [17]:
pdesthoshab = pdesthoshab.rename(columns={'cod_esthab':'est_hab'})
pdesthoshab['est_hab'] = pdesthoshab['est_hab'].str.strip()
pdhabitacionesv6 = pd.merge(pdhabitacionesv5,pdesthoshab,how='left',on='est_hab')

In [18]:
pdhabitacionesv6

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,est_reg,des_are,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tiphab,des_esthab
0,1,1,076,03,D11,04,01,"A,B,C",3,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE,NORMAL
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,0,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL
4,5,1,076,03,C11,03,02,"A,B",1,1,1,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,GINECOLOGIA Y OBSTETRICIA ...,COMUN,NORMAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,1,HOSPITALIZACION,34.0,H.II JAEN,40,RED ASISTENCIAL JAEN ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,1,URGENCIAS / EMERGENCIA,9.0,H.I PACASMAYO,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD,MEDICINA GENERAL ...,COMUN,NORMAL
16412,16413,1,001,03,B63,07,124,13C,1,1,1,HOSPITALIZACION,3.0,H.N. EDGARDO REBAGLIATI MARTINS,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD,NEUROCIRUGIA VASCULAR Y TUMORES / CIR.CEREB.Y ...,COMUN,NORMAL
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,1,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL

In [19]:
pdestreg = pdestreg.rename(columns={'cod_est':'est_reg'})
pdhabitacionesv7 = pd.merge(pdhabitacionesv6,pdestreg,how='left',on='est_reg')

In [20]:
pdhabitacionesv7

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,...,des_are,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tiphab,des_esthab,des_est
0,1,1,076,03,D11,04,01,"A,B,C",3,1,...,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE,NORMAL,INACTIVO / ANULADO / PASIVO
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,...,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,...,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,...,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO
4,5,1,076,03,C11,03,02,"A,B",1,1,...,HOSPITALIZACION,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,GINECOLOGIA Y OBSTETRICIA ...,COMUN,NORMAL,ACTIVO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16410,16411,1,245,03,D11,09,01,2DO PISO,1,1,...,HOSPITALIZACION,34.0,H.II JAEN,40,RED ASISTENCIAL JAEN ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO
16411,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,...,URGENCIAS / EMERGENCIA,9.0,H.I PACASMAYO,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD,MEDICINA GENERAL ...,COMUN,NORMAL,ACTIVO
16412,16413,1,001,03,B63,07,124,13C,1,1,...,HOSPITALIZACION,3.0,H.N. EDGARDO REBAGLIATI MARTINS,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD,NEUROCIRUGIA VASCULAR Y TUMORES / CIR.CEREB.Y ...,COMUN,NORMAL,ACTIVO
16413,16414,1,149,03,D11,04,036,EX COVID,1,1,...,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO
16414,16415,1,149,03,D11,04,037,EX COVID,1,1,...,HOSPITALIZACION,13.0,H.III DANIEL ALCIDES CARRION,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO

In [21]:
pdestenf['key1'] = pdestenf.apply(lambda row: f"{row['ori_cas']}_{row['estenf_cod_cas']}_{row['estenf_are_cod']}_{row['estenf_serv_cod']}_{row['est_cod']}", axis=1)

In [22]:
pdhabitacionesv7['key1'] = pdhabitacionesv7.apply(lambda row: f"{row['ori_cas']}_{row['cas_cod']}_{row['are_cod']}_{row['ser_cod']}_{row['enf_cod']}", axis=1)

In [23]:
pdhabitacionesv7['key2'] = pdhabitacionesv7.apply(lambda row: f"{row['ori_cas']}_{row['cas_cod']}_{row['are_cod']}_{row['ser_cod']}_{row['enf_cod']}_{row['hab_cod']}", axis=1)

In [24]:
pdestenf = pdestenf.drop(columns=['ori_cas','estenf_cod_cas', 'estenf_are_cod','estenf_serv_cod','est_cod'])

In [25]:
pdhabitacionesv8 = pd.merge(pdhabitacionesv7,pdestenf,how='left',on='key1')

In [26]:
pdhabitacionesv8= pdhabitacionesv8.drop_duplicates()

In [27]:
pdhabitacionesv8 = pdhabitacionesv8.rename(columns={'est_reg':'hab_est_reg'})
pdhabitacionesv8 = pdhabitacionesv8.rename(columns={'des_est':'hab_des_estreg'})
pdhabitacionesv8

,id_hab,ori_cas,cas_cod,are_cod,ser_cod,enf_cod,hab_cod,hab_ubi,tip_hab,est_hab,...,cod_red,des_red,ori_nom,des_ser,des_tiphab,des_esthab,hab_des_estreg,key1,key2,est_des
0,1,1,076,03,D11,04,01,"A,B,C",3,1,...,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,1_076_03_D11_04_01,PEDIATRIA
1,2,1,076,03,D11,04,03,"A,B,C,D",1,1,...,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,1_076_03_D11_04_03,PEDIATRIA
2,3,1,076,03,D11,04,04,"A,B,C,D",1,1,...,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,1_076_03_D11_04_04,PEDIATRIA
3,4,1,076,03,D11,04,05,"A,B,C,D",1,1,...,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,1_076_03_D11_04_05,PEDIATRIA
4,5,1,076,03,C11,03,02,"A,B",1,1,...,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,GINECOLOGIA Y OBSTETRICIA ...,COMUN,NORMAL,ACTIVO,1_076_03_C11_03,1_076_03_C11_03_02,OBSTETRICIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16427,16411,1,245,03,D11,09,01,2DO PISO,1,1,...,40,RED ASISTENCIAL JAEN ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO,1_245_03_D11_09,1_245_03_D11_09_01,ALOJAMIENTO CONJUNTO
16428,16412,1,208,02,AB1,01,0001,OBSERVACION,1,1,...,15,RED ASISTENCIAL LA LIBERTAD ...,ESSALUD,MEDICINA GENERAL ...,COMUN,NORMAL,ACTIVO,1_208_02_AB1_01,1_208_02_AB1_01_0001,EST. ENF. ENFERMERIA
16429,16413,1,001,03,B63,07,124,13C,1,1,...,07,RED PRESTACIONAL REBAGLIATI ...,ESSALUD,NEUROCIRUGIA VASCULAR Y TUMORES / CIR.CEREB.Y ...,COMUN,NORMAL,ACTIVO,1_001_03_B63_07,1_001_03_B63_07_124,CIR.VERT.NER.PER.13C
16430,16414,1,149,03,D11,04,036,EX COVID,1,1,...,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO,1_149_03_D11_04,1_149_03_D11_04_036,ESTACIÓN PEDIATRÍA
16431,16415,1,149,03,D11,04,037,EX COVID,1,1,...,21,RED ASISTENCIAL TACNA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,ACTIVO,1_149_03_D11_04,1_149_03_D11_04_037,ESTACIÓN PEDIATRÍA

In [28]:
pdcamasv2 = pd.merge(pdcamas,ori_cas_red,how='left',on='cas_cod')

In [29]:
pdcamasv2

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,cam_obs,est_reg,cam_flg,id_red,des_cas,cod_red,des_red,ori_nom
0,1,1,265,AC1,02,0004,17,1,5,03,...,0,0,5.0,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD
1,2,1,076,D11,04,01,01,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
2,3,1,076,D11,04,03,A,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
3,4,1,076,D11,04,03,D,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
4,5,1,076,D11,04,04,B,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,0,0,10.0,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,0,0,12.0,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD
66165,66166,1,307,A71,01,311,311B,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,0,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD

In [30]:
pdcamasv3 = pd.merge(pdcamasv2,pdservicios,how='left',on='ser_cod')

In [31]:
pdcamasv3

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,cam_obs,est_reg,cam_flg,id_red,des_cas,cod_red,des_red,ori_nom,des_ser
0,1,1,265,AC1,02,0004,17,1,5,03,...,0,0,5.0,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...
1,2,1,076,D11,04,01,01,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
2,3,1,076,D11,04,03,A,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
3,4,1,076,D11,04,03,D,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
4,5,1,076,D11,04,04,B,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,0,0,10.0,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,0,0,12.0,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...
66165,66166,1,307,A71,01,311,311B,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,0,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...

In [32]:
pdtiphoscam = pdtiphoscam.rename(columns={'cod_tipcam':'tip_cam'})
pdtiphoscam['tip_cam'] = pdtiphoscam['tip_cam'].str.strip()
pdcamasv4 = pd.merge(pdcamasv3,pdtiphoscam,how='left',on='tip_cam')

In [33]:
pdcamasv4

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,cam_obs,est_reg,cam_flg,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tipcam
0,1,1,265,AC1,02,0004,17,1,5,03,...,0,0,5.0,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...,CAMA
1,2,1,076,D11,04,01,01,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL
2,3,1,076,D11,04,03,A,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL
3,4,1,076,D11,04,03,D,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL
4,5,1,076,D11,04,04,B,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,0,0,10.0,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...,CAMA
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,0,0,12.0,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...,CAMA
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA
66165,66166,1,307,A71,01,311,311B,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...,CAMA
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,0,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA

In [34]:
pdcamasv5 = pd.merge(pdcamasv4,pdareas,how='left',on='are_cod')
pdcamasv5

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,...,est_reg,cam_flg,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tipcam,des_are
0,1,1,265,AC1,02,0004,17,1,5,03,...,0,0,5.0,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION
1,2,1,076,D11,04,01,01,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION
2,3,1,076,D11,04,03,A,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION
3,4,1,076,D11,04,03,D,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION
4,5,1,076,D11,04,04,B,2,6,03,...,0,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,0,0,10.0,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,0,0,12.0,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...,CAMA,HOSPITALIZACION
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION
66165,66166,1,307,A71,01,311,311B,1,2,03,...,1,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...,CAMA,HOSPITALIZACION
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,0,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION

In [35]:
pdesthoscam = pdesthoscam.rename(columns={'cod_estcam':'est_cam'})
pdesthoscam['est_cam'] = pdesthoscam['est_cam'].str.strip()
pdcamasv6 = pd.merge(pdcamasv5,pdesthoscam,how='left',on='est_cam')

In [36]:
pdcamasv6

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,...,cam_flg,id_red,des_cas,cod_red,des_red,ori_nom,des_ser,des_tipcam,des_are,des_estcam
0,1,1,265,AC1,02,0004,17,1,5,03,...,0,5.0,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION,SUSPENDIDA
1,2,1,076,D11,04,01,01,2,6,03,...,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION,BAJA
2,3,1,076,D11,04,03,A,2,6,03,...,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION,BAJA
3,4,1,076,D11,04,03,D,2,6,03,...,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION,BAJA
4,5,1,076,D11,04,04,B,2,6,03,...,0,11.0,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INFANTIL,HOSPITALIZACION,BAJA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,0,10.0,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION,DISPONIBLE
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,0,12.0,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...,CAMA,HOSPITALIZACION,DISPONIBLE
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION,OCUPADA
66165,66166,1,307,A71,01,311,311B,1,2,03,...,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...,CAMA,HOSPITALIZACION,OCUPADA
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,0,19.0,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,CAMA,HOSPITALIZACION,BAJA

In [37]:
pdcamasv6 = pdcamasv6.rename(columns={'est_reg':'cama_est_reg'})
pdcamasv6 = pdcamasv6.rename(columns={'des_est':'cama_des_estreg'})

In [38]:
pdcamasv6['key1'] = pdcamasv6.apply(lambda row: f"{row['ori_cas']}_{row['cas_cod']}_{row['are_cod']}_{row['ser_cod']}_{row['enf_cod']}", axis=1)

In [39]:
pdcamasv6['key2'] = pdcamasv6.apply(lambda row: f"{row['ori_cas']}_{row['cas_cod']}_{row['are_cod']}_{row['ser_cod']}_{row['enf_cod']}_{row['hab_cod']}", axis=1)

In [40]:
pdcamasv7 = pd.merge(pdcamasv6,pdhabitacionesv8,how='left',on='key2')

In [41]:
pdcamasv7

,id_cama,ori_cas_x,cas_cod_x,ser_cod_x,enf_cod_x,hab_cod_x,cam_cod,tip_cam,est_cam,are_cod_x,...,des_cas_y,cod_red_y,des_red_y,ori_nom_y,des_ser_y,des_tiphab,des_esthab,hab_des_estreg,key1_y,est_des
0,1,1,265,AC1,02,0004,17,1,5,03,...,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...,COMUN,NORMAL,ACTIVO,1_265_03_AC1_02,HOSP.MEDICINA
1,2,1,076,D11,04,01,01,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
2,3,1,076,D11,04,03,A,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
3,4,1,076,D11,04,03,D,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
4,5,1,076,D11,04,04,B,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...,INDEPENDIENTE,EN CUARENTENA,ACTIVO,1_161_03_AC1_35,ESTAC. HOSP.MEDICINA
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_136_03_AK1_03,UCIN
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_AC1_08,MED ESPECIALIZADA
66165,66166,1,307,A71,01,311,311B,1,2,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_A71_01,GERIATRIA 1
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_AC1_04,MEDICINA INTERNA 4

In [42]:
#pdcamasv7.columns

In [43]:
#for column in pdcamasv7.columns:
#    if column.endswith("_x"):
#        corresponding_column = column.replace("_x", "_y")
#        pdcamasv7[f'{column}_different'] = pdcamasv7[column] != pdcamasv7[corresponding_column]

In [44]:
#pdcamasv7

In [45]:
#for column in pdcamasv7.columns:
#    if column.endswith("_different"):
#        true_count = pdcamasv7[column].sum()
#        print(f'En la columna {column}: {true_count} True')

In [46]:
pdcamasv7

,id_cama,ori_cas_x,cas_cod_x,ser_cod_x,enf_cod_x,hab_cod_x,cam_cod,tip_cam,est_cam,are_cod_x,...,des_cas_y,cod_red_y,des_red_y,ori_nom_y,des_ser_y,des_tiphab,des_esthab,hab_des_estreg,key1_y,est_des
0,1,1,265,AC1,02,0004,17,1,5,03,...,H.II JORGE REATEGUI DELGADO,09,RED ASISTENCIAL PIURA ...,ESSALUD,MEDICINA INTERNA ...,COMUN,NORMAL,ACTIVO,1_265_03_AC1_02,HOSP.MEDICINA
1,2,1,076,D11,04,01,01,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,INDEPENDIENTE,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
2,3,1,076,D11,04,03,A,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
3,4,1,076,D11,04,03,D,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
4,5,1,076,D11,04,04,B,2,6,03,...,H.III YANAHUARA,18,RED ASISTENCIAL AREQUIPA ...,ESSALUD,PEDIATRIA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_076_03_D11_04,PEDIATRIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,H.III CHIMBOTE,16,RED ASISTENCIAL ANCASH ...,ESSALUD,MEDICINA INTERNA ...,INDEPENDIENTE,EN CUARENTENA,ACTIVO,1_161_03_AC1_35,ESTAC. HOSP.MEDICINA
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,H.II MOQUEGUA,20,RED ASISTENCIAL MOQUEGUA ...,ESSALUD,MEDICINA INTENSIVA ...,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,1_136_03_AK1_03,UCIN
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_AC1_08,MED ESPECIALIZADA
66165,66166,1,307,A71,01,311,311B,1,2,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,GERIATRIA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_A71_01,GERIATRIA 1
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,H.N. RAMIRO PRIALE PRIALE,27,RED ASISTENCIAL JUNIN ...,ESSALUD,MEDICINA INTERNA ...,BIPERSONAL,NORMAL,ACTIVO,1_307_03_AC1_04,MEDICINA INTERNA 4

In [47]:
# Identifica y elimina las columnas duplicadas con sufijo "_y"
duplicadas_y = [col for col in pdcamasv7.columns if col.endswith('_y')]
pdcamasv7 = pdcamasv7.drop(columns=duplicadas_y)
# Quitar el sufijo "_x" de las columnas
pdcamasv7.columns = pdcamasv7.columns.str.rstrip('_x')

In [49]:
pdcamasv7

,id_cama,ori_cas,cas_cod,ser_cod,enf_cod,hab_cod,cam_cod,tip_cam,est_cam,are_cod,...,key2,id_hab,hab_ubi,tip_hab,est_hab,hab_est_reg,des_tiphab,des_esthab,hab_des_estreg,est_des
0,1,1,265,AC1,02,0004,17,1,5,03,...,1_265_03_AC1_02_0004,96,MEDICINA,1,1,1,COMUN,NORMAL,ACTIVO,HOSP.MEDICINA
1,2,1,076,D11,04,01,01,2,6,03,...,1_076_03_D11_04_01,1,"A,B,C",3,1,0,INDEPENDIENTE,NORMAL,INACTIVO / ANULADO / PASIVO,PEDIATRIA
2,3,1,076,D11,04,03,A,2,6,03,...,1_076_03_D11_04_03,2,"A,B,C,D",1,1,0,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,PEDIATRIA
3,4,1,076,D11,04,03,D,2,6,03,...,1_076_03_D11_04_03,2,"A,B,C,D",1,1,0,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,PEDIATRIA
4,5,1,076,D11,04,04,B,2,6,03,...,1_076_03_D11_04_04,3,"A,B,C,D",1,1,0,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,PEDIATRIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66162,66163,1,161,AC1,35,S009,00232,1,1,03,...,1_161_03_AC1_35_S009,15170,HOSP. MEDI. INTERNA,3,2,1,INDEPENDIENTE,EN CUARENTENA,ACTIVO,ESTAC. HOSP.MEDICINA
66163,66164,1,136,AK1,03,UCIN,6,1,1,03,...,1_136_03_AK1_03_UCIN,10164,UCIN,1,1,0,COMUN,NORMAL,INACTIVO / ANULADO / PASIVO,UCIN
66164,66165,1,307,AC1,08,445,445A,1,2,03,...,1_307_03_AC1_08_445,15998,4TO PISO,2,1,1,BIPERSONAL,NORMAL,ACTIVO,MED ESPECIALIZADA
66165,66166,1,307,A71,01,311,311B,1,2,03,...,1_307_03_A71_01_311,15696,3ER PISO,2,1,1,BIPERSONAL,NORMAL,ACTIVO,GERIATRIA 1
66166,66167,1,307,AC1,04,346,346A,1,6,03,...,1_307_03_AC1_04_346,3829,3ER PISO,2,1,1,BIPERSONAL,NORMAL,ACTIVO,MEDICINA INTERNA 4

In [52]:
pdcamasv7.to_sql(name=f'dm_hosp_camas', con=connection4, if_exists='append', index=False,chunksize=10000)

6167

In [48]:
connection4.close()