In [82]:
import pandas as pd
import numpy as np

In [84]:
df1.head()

,DNI,NOMBRES,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO,CENTRO ASISTENCIAL,RED,AÑO,SEMANA EPIDEMIOLÓGICA,TIPO DE CASO,GRUPO ETAREO,ETAPA DE VIDA
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,ADULTO MAYOR
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,ADULTO
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,JOVEN
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,NIÑO
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,NIÑO

In [85]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65904 entries, 0 to 65903
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   DNI                         65904 non-null  object
 1   NOMBRE                      65904 non-null  object
 2   SEXO                        65904 non-null  object
 3   EDAD                        65904 non-null  int64
 4   INGRESO-INICIO DE SINTOMAS  65904 non-null  datetime64[ns]
 5   DIAGNÓSTICO                 65904 non-null  object
 6   CENTRO ASISTENCIAL          65904 non-null  object
 7   RED                         65904 non-null  object
 8   AÑO                         65904 non-null  int64
 9   SEMANA                      65904 non-null  int64
 10  CASO                        65904 non-null  object
 11  GRUPO ETAREO                65904 non-null  object
 12  ETAPA DE VIDA               65904 non-null  object
dtypes: datetime64[ns](1), int64(3), object(9)
memory usage: 6.5+ MB

In [86]:
df1.rename(columns={'NOMBRES': 'NOMBRE', 'SEMANA EPIDEMIOLÓGICA': 'SEMANA', 'TIPO DE CASO': 'CASO'}, inplace=True)
df1.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,ADULTO MAYOR
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,ADULTO
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,JOVEN
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,NIÑO
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,NIÑO

In [87]:
df = pd.concat([df1,df2], ignore_index=True)

In [88]:
df.tail()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA
221598,06572388,TADEO LOPEZ LUCILA CARMEN,73,F,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,70 - 74 AÑOS,ADULTO MAYOR
221599,72596439,LUCERO GARCIA FRANCO JOSUE,15,M,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,15 - 19 AÑOS,ADOLESCENTE
221600,74518653,BALDARRAGO PANDO ALEXIS FABIAN,13,M,2024-04-04,A97.0,POL. JUAN JOSÉ RODRÍGUEZ LAZO,REBAGLIATI,2024,14,PROBABLE,10 - 14 AÑOS,ADOLESCENTE
221601,62054921,MARMOLEJO VALVERDE GUADALUPE FATIMA,15,F,2024-04-04,A97.0,H.II HUÁNUCO,HUÁNUCO,2024,14,PROBABLE,15 - 19 AÑOS,ADOLESCENTE
221602,80111572,RIOS SALAZAR YESSICA KARIN,46,F,2024-04-04,A97.0,H.II HUÁNUCO,HUÁNUCO,2024,14,PROBABLE,45- 49 AÑOS,ADULTO

In [89]:
df['ETAPA DE VIDA'] = np.nan
df.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,NaN
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,NaN
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,NaN
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,NaN
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,NaN

In [90]:
# Define conditions and replacement values
conditions = [
    (df['EDAD'] >= 0) & (df['EDAD'] <= 11),
    (df['EDAD'] >= 12) & (df['EDAD'] <= 17),
    (df['EDAD'] >= 18) & (df['EDAD'] <= 29),
    (df['EDAD'] >= 30) & (df['EDAD'] <= 59),
    (df['EDAD'] >= 60)
]
values = [
    'GE01: Niño',
    'GE02: Adolescente',
    'GE03: Joven',
    'GE04: Adulto',
    'GE05: Adulto Mayor'
]

# Replace NaN values in 'ETAPA DE VIDA' based on 'EDAD' conditions
df['ETAPA DE VIDA'] = np.where(pd.isnull(df['ETAPA DE VIDA']),
                               np.select(conditions, values, default='Unknown'),
                               df['ETAPA DE VIDA'])

In [91]:
df.tail(50)

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA
221553,75990820,SOCOLA CARRION PEDRO,19,M,2024-04-03,A97.0,POL. HOSPITAL UNIVERSITARIO,PIURA,2024,14,PROBABLE,15 - 19 AÑOS,GE03: Joven
221554,43003594,ZURITA RAMIREZ MONICA,38,F,2024-04-03,A97.0,POL. INMACULADA CONCEPCION,PIURA,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221555,08810842,SOTELO VELASQUEZ DE NEVADO AIDA,63,F,2024-04-03,A97.0,POL. JUAN JOSÉ RODRÍGUEZ LAZO,REBAGLIATI,2024,14,PROBABLE,60 - 64 AÑOS,GE05: Adulto Mayor
221556,09859719,CALDERON VALVERDE ANALY,48,F,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,45- 49 AÑOS,GE04: Adulto
221557,75723425,CHUICA MEDINA BLANCA,29,F,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,25 - 29 AÑOS,GE03: Joven
221558,62735131,SAAVEDRA CCENCHO LUIS,24,M,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,20 - 24 AÑOS,GE03: Joven
221559,40178389,BENITES ALIAGA MIGUEL,45,M,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,45- 49 AÑOS,GE04: Adulto
221560,78484204,LINARES TAFUR DYLAN,10,M,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,10 - 14 AÑOS,GE01: Niño
221561,47401304,TOLEDO VALDEZ HOUSTON,31,M,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,30 - 34 AÑOS,GE04: Adulto
221562,78170691,RODRIGUEZ CABALLERO LUHA,10,F,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,10 - 14 AÑOS,GE01: Niño
221563,90329523,RODRIGUEZ CABALLERO LEAH,6,F,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,5 - 9 AÑOS,GE01: Niño
221564,73683757,VILLANUEVA ATANACIO YESENIA,23,F,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,20 - 24 AÑOS,GE03: Joven
221565,10743565,VERAMENDI BENANCIO MENEN,59,M,2024-04-03,A97.0,POL. POL.COMPLEJIDAD CRECIENTE EL RETABLO,SABOGAL,2024,14,PROBABLE,55 - 59 AÑOS,GE04: Adulto
221566,78182401,SAMAM+ MEDINA MARIAGRAZIA,10,F,2024-04-03,A97.1,H.N. EDGARDO REBAGLIATI MARTINS,REBAGLIATI,2024,14,PROBABLE,10 - 14 AÑOS,GE01: Niño
221567,78796093,VASQUEZ TACUCHI JUAN JOSE,21,M,2024-04-03,A97.0,H.II RAMÓN CASTILLA,ALMENARA,2024,14,PROBABLE,20 - 24 AÑOS,GE03: Joven
221568,22245857,BASALDUA PALOMINO REYNA ISABEL,63,F,2024-04-03,A97.0,H.II RAMÓN CASTILLA,ALMENARA,2024,14,PROBABLE,60 - 64 AÑOS,GE05: Adulto Mayor
221569,72524251,PEREZ VERA ROSMERY KARINA,29,F,2024-04-03,A97.0,H.I MOCHE,LA LIBERTAD,2024,14,PROBABLE,25 - 29 AÑOS,GE03: Joven
221570,70390721,BENDEZU BOJORGE ANABEL YOLANDA,33,F,2024-04-03,A97.0,H.II RENÉ TOCHE GROPPO,ICA,2024,14,PROBABLE,30 - 34 AÑOS,GE04: Adulto
221571,21811775,GARAY CARBAJAL LEONARDO JULIO,57,M,2024-04-03,A97.0,H.II RENÉ TOCHE GROPPO,ICA,2024,14,PROBABLE,55 - 59 AÑOS,GE04: Adulto
221572,21578305,VALENZUELA SUAREZ RICHARD ANTONIO,46,M,2024-04-03,A97.0,C.A.P.II SANTA MARGARITA,ICA,2024,14,PROBABLE,45- 49 AÑOS,GE04: Adulto
221573,61077004,SINTI JIMENEZ CHELSY LUCERO,17,F,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,15 - 19 AÑOS,GE02: Adolescente
221574,42953429,ARANGO OLARTE JULIA,38,F,2024-04-03,A97.0,H.N. EDGARDO REBAGLIATI MARTINS,REBAGLIATI,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221575,70466587,VALDIVIA HERRERA GINA STEFFANY,31,F,2024-04-03,A97.0,H.II RENÉ TOCHE GROPPO,ICA,2024,14,PROBABLE,30 - 34 AÑOS,GE04: Adulto
221576,61245691,FASABI TANCHIVA HECTOR MIGUEL,16,M,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,15 - 19 AÑOS,GE02: Adolescente
221577,45854726,CONDEZO DURAN LUZ GABRIELA,35,F,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221578,93074516,HUAYABAN VASQUEZ RUSSELL TEDY,1,M,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,0 - 4 AÑOS,GE01: Niño
221579,00021259,DIAZ CORTEZ GENITH,69,F,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,65 - 69 AÑOS,GE05: Adulto Mayor
221580,00152321,VILLACREZ PANDURO ANITA,57,F,2024-04-03,A97.0,H.II PUCALLPA,UCAYALI,2024,14,PROBABLE,55 - 59 AÑOS,GE04: Adulto
221581,48085597,MONTALVAN RODRIGUEZ JULIO ABEL,30,M,2024-04-03,A97.0,POL. FIORI,SABOGAL,2024,14,PROBABLE,30 - 34 AÑOS,GE04: Adulto
221582,43874616,PRADO DIAZ JAVIER,38,M,2024-04-03,A97.0,H.III H.E. ALBERTO LEOPOLDO BARTON THOMPSON,SABOGAL,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221583,09726311,LOPEZ HUARANGAY MARIA GUADALUPE,54,F,2024-04-03,A97.0,POL. CHOSICA,ALMENARA,2024,14,PROBABLE,50 - 54 AÑOS,GE04: Adulto
221584,07670934,AYALA QUEVEDO VDA DE YALLO MANUELA ESTHER,68,F,2024-04-03,A97.0,POL. CHOSICA,ALMENARA,2024,14,PROBABLE,65 - 69 AÑOS,GE05: Adulto Mayor
221585,07672972,CHOCÐA VICENTE EUGENIA,58,F,2024-04-03,A97.0,POL. CHOSICA,ALMENARA,2024,14,PROBABLE,55 - 59 AÑOS,GE04: Adulto
221586,47475823,TORRES CASAPERALTA JHON SMITH,31,M,2024-04-03,A97.0,POL. CHOSICA,ALMENARA,2024,14,PROBABLE,30 - 34 AÑOS,GE04: Adulto
221587,09223514,MANTURANO MARTINEZ ANGELICA,66,F,2024-04-03,A97.0,POL. CHOSICA,ALMENARA,2024,14,PROBABLE,65 - 69 AÑOS,GE05: Adulto Mayor
221588,74666934,ARANDA LAURENTE SEBASTIAN,13,M,2024-04-03,A97.0,H.I JORGE VOTO BERNALES CORPANCHO,ALMENARA,2024,14,PROBABLE,10 - 14 AÑOS,GE02: Adolescente
221589,44611723,CHINCHAY JAIME JORDAN LEONEL,36,M,2024-04-03,A97.0,C.A.P.II SAN IGNACIO,JAÉN,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221590,70241287,HUANES CASTILLO JOSE SEBASTIAN,26,M,2024-04-03,A97.0,C.A.P.II SAN IGNACIO,JAÉN,2024,14,PROBABLE,25 - 29 AÑOS,GE03: Joven
221591,78470069,LOPEZ SANDOVAL RENATO GABRIEL,10,M,2024-04-03,A97.0,H.I TINGO MARÍA,HUÁNUCO,2024,14,PROBABLE,10 - 14 AÑOS,GE01: Niño
221592,43909806,SUASNABAR CUCHO CHRISTIAN HENRY,37,M,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,35 - 39 AÑOS,GE04: Adulto
221593,61075513,PAUCAR LESCANO JEFERSSON RUSEMBEL,16,M,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,15 - 19 AÑOS,GE02: Adolescente
221594,75722422,ARRIARAN SALAZAR LUCERO MARIANELA,28,F,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,25 - 29 AÑOS,GE03: Joven
221595,07052683,ESPINOZA CHOQUE MARIA,83,F,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,80 - 84 AÑOS,GE05: Adulto Mayor
221596,61929747,COVEÐAS OJEDA ANGEL SEGUNDO,14,M,2024-04-03,A97.0,C.M. TAMBOGRANDE,PIURA,2024,14,PROBABLE,10 - 14 AÑOS,GE02: Adolescente
221597,41551343,HUAMANCHAHUA TINEO ELIZABETH,41,F,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,40 - 44 AÑOS,GE04: Adulto
221598,06572388,TADEO LOPEZ LUCILA CARMEN,73,F,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,70 - 74 AÑOS,GE05: Adulto Mayor
221599,72596439,LUCERO GARCIA FRANCO JOSUE,15,M,2024-04-03,A97.0,H.II VITARTE,ALMENARA,2024,14,PROBABLE,15 - 19 AÑOS,GE02: Adolescente
221600,74518653,BALDARRAGO PANDO ALEXIS FABIAN,13,M,2024-04-04,A97.0,POL. JUAN JOSÉ RODRÍGUEZ LAZO,REBAGLIATI,2024,14,PROBABLE,10 - 14 AÑOS,GE02: Adolescente
221601,62054921,MARMOLEJO VALVERDE GUADALUPE FATIMA,15,F,2024-04-04,A97.0,H.II HUÁNUCO,HUÁNUCO,2024,14,PROBABLE,15 - 19 AÑOS,GE02: Adolescente
221602,80111572,RIOS SALAZAR YESSICA KARIN,46,F,2024-04-04,A97.0,H.II HUÁNUCO,HUÁNUCO,2024,14,PROBABLE,45- 49 AÑOS,GE04: Adulto

In [92]:
CASOS = df['CASO'].unique()
print(CASOS)

['CONFIRMADO' 'PROBABLE']

In [93]:
REDES = df['RED'].unique()
print(REDES)

['PIURA' 'TUMBES' 'HUANUCO' 'MADRE DE DIOS' 'JAEN' 'LORETO' 'AMAZONAS'
 'TARAPOTO' 'MOYOBAMBA' 'LAMBAYEQUE' 'JUNIN' 'UCAYALI' 'ICA' 'REBAGLIATI'
 'AYACUCHO' 'CUSCO' 'AREQUIPA' 'SABOGAL' 'ALMENARA' 'PASCO' 'CAJAMARCA'
 'LA LIBERTAD' 'JULIACA' 'ANCASH' 'MOQUEGUA' 'PUNO' 'HUARAZ'
 'HUANCAVELICA' 'TACNA' 'APURIMAC' 'JUNÍN' 'JAÉN' 'HUÁNUCO' 'APURÍMAC']

In [94]:
df['RED'].value_counts()

RED
PIURA            61383
LAMBAYEQUE       52514
ICA              28031
LA LIBERTAD      17900
ANCASH           13313
SABOGAL          10290
ALMENARA          7598
TUMBES            6294
REBAGLIATI        3599
MOYOBAMBA         3282
JAEN              3031
UCAYALI           2823
TARAPOTO          2337
LORETO            1826
MADRE DE DIOS     1270
AMAZONAS          1257
HUANUCO           1195
JUNIN              987
CUSCO              889
CAJAMARCA          498
JAÉN               359
JUNÍN              213
AYACUCHO           193
HUÁNUCO            186
PASCO              125
HUARAZ              67
JULIACA             44
AREQUIPA            38
HUANCAVELICA        20
MOQUEGUA            15
TACNA               15
APURÍMAC             6
PUNO                 3
APURIMAC             2
Name: count, dtype: int64

In [95]:
CONTEOS = df.nunique()
print(CONTEOS)

DNI                           217823
NOMBRE                        219103
EDAD                             104
SEXO                               2
INGRESO-INICIO DE SINTOMAS       461
DIAGNÓSTICO                        3
CENTRO ASISTENCIAL               497
RED                               34
AÑO                                2
SEMANA                            52
CASO                               2
GRUPO ETAREO                      18
ETAPA DE VIDA                      5
dtype: int64

In [96]:
df.rename(columns={'DIAGNÓSTICO': 'DIAGNÓSTICO CIE_10'}, inplace=True)
df.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO CIE_10,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,GE05: Adulto Mayor
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,GE04: Adulto
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,GE03: Joven
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño

In [97]:
# Define conditions and replacement values
conditions = [
    df['DIAGNÓSTICO CIE_10'] == 'A97.0',
    df['DIAGNÓSTICO CIE_10'] == 'A97.1',
    df['DIAGNÓSTICO CIE_10'] == 'A97.2'
]
values = [
    'DENGUE SIN SEÑALES DE ALARMA',
    'DENGUE CON SEÑALES DE ALARMA',
    'DENGUE GRAVE'
]

# Create new 'DIAGNÓSTICO' column based on 'DIAGNÓSTICO CIE_10' values
df['DIAGNÓSTICO'] = np.select(conditions, values, default='OTHER')

In [98]:
df.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO CIE_10,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA,DIAGNÓSTICO
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,GE05: Adulto Mayor,DENGUE SIN SEÑALES DE ALARMA
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,GE03: Joven,DENGUE SIN SEÑALES DE ALARMA
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño,DENGUE SIN SEÑALES DE ALARMA
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño,DENGUE SIN SEÑALES DE ALARMA

In [99]:
print(df['DIAGNÓSTICO'].unique())

['DENGUE SIN SEÑALES DE ALARMA' 'DENGUE CON SEÑALES DE ALARMA'
 'DENGUE GRAVE']

In [100]:
print(df['CASO'].unique())

['CONFIRMADO' 'PROBABLE']

In [101]:
# Filter the DataFrame based on the 'INGRESO-INICIO DE SÍNTOMAS' column
df_2024 = df[df['INGRESO-INICIO DE SINTOMAS'] >= '2023-12-31']

In [102]:
df_2023 = df[df['INGRESO-INICIO DE SINTOMAS'] < '2023-12-31']

In [103]:
df_2024.reset_index(drop=True, inplace=True)

In [104]:
df_2024.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO CIE_10,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA,DIAGNÓSTICO
0,03656673,YOVERA INGA CARMEN,54,M,2023-12-31,A97.0,H.I SULLANA,PIURA,2023,1,CONFIRMADO,50 - 54 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA
1,17528625,ROJAS CHACHAPOYAS ELIZABETH,59,F,2023-12-31,A97.0,POL. AGUSTIN GAVIDIA SALCEDO,LAMBAYEQUE,2023,1,CONFIRMADO,55 - 59 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA
2,17615686,HUERTAS BANCES JESUS SANTIAGO,53,M,2023-12-31,A97.0,POL. AGUSTIN GAVIDIA SALCEDO,LAMBAYEQUE,2023,1,CONFIRMADO,50 - 54 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA
3,21433312,ARANGO TINEO ELIZABETH LIDIA,64,F,2023-12-31,A97.0,H.I FÉLIX TORREALVA GUTIÉRREZ,ICA,2023,1,CONFIRMADO,60 - 64 AÑOS,GE05: Adulto Mayor,DENGUE SIN SEÑALES DE ALARMA
4,21462590,GALLEGOS VARGAS JULIO CESAR,55,M,2023-12-31,A97.0,H.I FÉLIX TORREALVA GUTIÉRREZ,ICA,2023,1,CONFIRMADO,55 - 59 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA

In [105]:
df_2023.head()

,DNI,NOMBRE,EDAD,SEXO,INGRESO-INICIO DE SINTOMAS,DIAGNÓSTICO CIE_10,CENTRO ASISTENCIAL,RED,AÑO,SEMANA,CASO,GRUPO ETAREO,ETAPA DE VIDA,DIAGNÓSTICO
0,03312331,CALLE NUÐEZ YNES,83,F,2023-01-05,A97.0,CAP II CHULUCANAS,PIURA,2023,1,CONFIRMADO,80 - 84 AÑOS,GE05: Adulto Mayor,DENGUE SIN SEÑALES DE ALARMA
1,41191403,ZEÐA PECHE ELIZABETH ELVIRA,41,F,2023-01-02,A97.0,H.I CARLOS ALBERTO CORTÉZ JIMÉNEZ,TUMBES,2023,1,CONFIRMADO,40 - 44 AÑOS,GE04: Adulto,DENGUE SIN SEÑALES DE ALARMA
2,72923192,TALLEDO ULFE CARLOS,29,M,2023-01-01,A97.0,H.II JORGE REÁTEGUI DELGADO,PIURA,2023,1,CONFIRMADO,25 - 29 AÑOS,GE03: Joven,DENGUE SIN SEÑALES DE ALARMA
3,79055433,DEL CASTILLO SALVATIERRA SAM AXEL,7,M,2023-01-06,A97.0,H.I TINGO MARÍA,HUANUCO,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño,DENGUE SIN SEÑALES DE ALARMA
4,79709710,RIVERA BOCANGELINO DIEGO ALEJANDRO,6,M,2023-01-07,A97.0,H.I VÍCTOR ALFREDO LAZO PERALTA,MADRE DE DIOS,2023,1,CONFIRMADO,5 - 9 AÑOS,GE01: Niño,DENGUE SIN SEÑALES DE ALARMA

In [106]:
# HACIENDO LOS CÁLCULOS PARA EL 2024

# Create a pivot table
pivot_table = pd.pivot_table(df_2024, 
                             values='DNI', 
                             index='SEXO', 
                             columns='ETAPA DE VIDA', 
                             aggfunc='count', 
                             fill_value=0)
#Display result
pivot_table

ETAPA DE VIDA,GE01: Niño,GE02: Adolescente,GE03: Joven,GE04: Adulto,GE05: Adulto Mayor
SEXO,,,,,
F,3812,3397,4527,17950,4878
M,4132,3904,5092,13873,4339

In [107]:
caso_counts = df_2024['CASO'].value_counts()
print(caso_counts)

CASO
PROBABLE      42465
CONFIRMADO    23439
Name: count, dtype: int64

In [108]:
AÑO_counts = df_2024['AÑO'].value_counts()
print(AÑO_counts)

AÑO
2024    65823
2023       81
Name: count, dtype: int64

In [109]:
# SEMANA EPIDEMIOLÓGICA PARA EL 2024

# Create a pivot table
pivot_table = pd.pivot_table(df_2024, 
                             values='DNI', 
                             index='SEMANA', 
                             aggfunc='count', 
                             fill_value=0)
#Display result
pivot_table

          DNI
SEMANA
1         949
2         877
3         995
4        1143
5        1729
6        2682
7        3645
8        4978
9        6846
10       7834
11       9894
12      10007
13       8620
14       5705

In [110]:
# SEMANA EPIDEMIOLÓGICA PARA EL 2023

# Create a pivot table
pivot_table = pd.pivot_table(df_2023, 
                             values='DNI', 
                             index='SEMANA', 
                             aggfunc='count', 
                             fill_value=0)
#Display result
pivot_table

          DNI
SEMANA
1         575
2         578
3         571
4         701
5         780
6         790
7         718
8         862
9         855
10        808
11       1205
12       1544
13       1860
14       1839
15       2682
16       3362
17       4176
18       6470
19       8583
20      12659
21      14068
22      13242
23      11795
24       9788
25       8026
26       6004
27       5110
28       4655
29       3868
30       2777
31       2871
32       2555
33       2248
34       2192
35       1800
36       1378
37       1348
38       1062
39        820
40        881
41        802
42        757
43        673
44        571
45        627
46        623
47        664
48        640
49        591
50        609
51        454
52        582

In [111]:
# Save the df_2024 DataFrame as a CSV file with ";" as the delimiter and 'utf-8' encoding
df_2024.to_csv('2024 - DENGUE VARIABLES.csv', sep=';', index=False, encoding='utf-8')

# Confirmation message
print("DataFrame saved successfully as '2024 - DENGUE VARIABLES.csv'")

DataFrame saved successfully as '2024 - DENGUE VARIABLES.csv'

In [112]:
# Save the df_2023 DataFrame as a CSV file with ";" as the delimiter and 'utf-8' encoding
df_2023.to_csv('2023 - DENGUE VARIABLES.csv', sep=';', index=False, encoding='utf-8')

# Confirmation message
print("DataFrame saved successfully as '2023 - DENGUE VARIABLES.csv'")

DataFrame saved successfully as '2023 - DENGUE VARIABLES.csv'

In [113]:
import os

In [114]:
cwd = os.getcwd()

print(f"CSV file saved in: {cwd}")

CSV file saved in: g:\DATASETS DENGUE